# Generated by Django 5.2.17 on 2026-09-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_institutionsetting_student_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accommodation',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='student',
            name='additional_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
