# Generated by Django 5.2.17 on 2026-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_accommodation_student_additional_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionsetting',
            name='accent_color',
            field=models.CharField(default='#d49a27', max_length=20),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='accommodation_label',
            field=models.CharField(default='Accommodation', max_length=80),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='additional_id_label',
            field=models.CharField(default='Additional ID', max_length=80),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='font_family',
            field=models.CharField(default='Arial, sans-serif', max_length=40),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='header_color',
            field=models.CharField(default='#123b63', max_length=20),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='institutionsetting',
            name='office',
            field=models.CharField(default='the Administration Office', max_length=160),
        ),
        migrations.AlterField(
            model_name='institutionsetting',
            name='name',
            field=models.CharField(default='Your Institution', max_length=160),
        ),
        migrations.AlterField(
            model_name='institutionsetting',
            name='primary_color',
            field=models.CharField(default='#123b63', max_length=20),
        ),
        migrations.AlterField(
            model_name='institutionsetting',
            name='secondary_color',
            field=models.CharField(default='#d49a27', max_length=20),
        ),
        migrations.AlterField(
            model_name='institutionsetting',
            name='signatory_name',
            field=models.CharField(default='Registrar', max_length=120),
        ),
    ]
